CREATE DATABASE Dados_scraping
CREATE TABLE ACOES (
    [Ticker] NVARCHAR(50),
    [Papel] NVARCHAR(50),
    [Cotação] NVARCHAR(50),
    [Tipo] NVARCHAR(50),
    [Data últ cot] NVARCHAR(50),
    [Empresa] NVARCHAR(255),
    [Min 52 sem] NVARCHAR(50),
    [Setor] NVARCHAR(100),
    [Max 52 sem] NVARCHAR(50),
    [Subsetor] NVARCHAR(100),
    [Vol $ méd (2m)] NVARCHAR(50),
    [Valor de mercado] NVARCHAR(50),
    [Últ balanço processado] NVARCHAR(50),
    [Valor da firma] NVARCHAR(50),
    [Nro. Ações] NVARCHAR(50),
    [Dia] NVARCHAR(50),
    [P/L] NVARCHAR(50),
    [LPA] NVARCHAR(50),
    [Mês] NVARCHAR(50),
    [P/VP] NVARCHAR(50),
    [VPA] NVARCHAR(50),
    [30 dias] NVARCHAR(50),
    [P/EBIT] NVARCHAR(50),
    [Marg. Bruta] NVARCHAR(50),
    [12 meses] NVARCHAR(50),
    [PSR] NVARCHAR(50),
    [Marg. EBIT] NVARCHAR(50),
    [2025] NVARCHAR(50),
    [P/Ativos] NVARCHAR(50),
    [Marg. Líquida] NVARCHAR(50),
    [2024] NVARCHAR(50),
    [P/Cap. Giro] NVARCHAR(50),
    [EBIT / Ativo] NVARCHAR(50),
    [2023] NVARCHAR(50),
    [P/Ativ Circ Liq] NVARCHAR(50),
    [ROIC] NVARCHAR(50),
    [2022] NVARCHAR(50),
    [Div. Yield] NVARCHAR(50),
    [ROE] NVARCHAR(50),
    [2021] NVARCHAR(50),
    [EV / EBITDA] NVARCHAR(50),
    [Liquidez Corr] NVARCHAR(50),
    [2020] NVARCHAR(50),
    [EV / EBIT] NVARCHAR(50),
    [Div Br/ Patrim] NVARCHAR(50),
    [Cres. Rec (5a)] NVARCHAR(50),
    [Giro Ativos] NVARCHAR(50),
    [Ativo] NVARCHAR(50),
    [Dív. Bruta] NVARCHAR(50),
    [Disponibilidades] NVARCHAR(50),
    [Dív. Líquida] NVARCHAR(50),
    [Ativo Circulante] NVARCHAR(50),
    [Patrim. Líq] NVARCHAR(50),
    [Receita Líquida] NVARCHAR(50),
    [Receita Líquida_1] NVARCHAR(50),  
    [EBIT] NVARCHAR(50),
    [EBIT_1] NVARCHAR(50),
    [Lucro Líquido] NVARCHAR(50),
    [Lucro Líquido_1] NVARCHAR(50),   
    [Depósitos] NVARCHAR(50),
    [Cart. de Crédito] NVARCHAR(50),
    [Result Int Financ] NVARCHAR(50),
    [Result Int Financ_1] NVARCHAR(50),     
    [Rec Serviços] NVARCHAR(50),
    [Rec Serviços_1] NVARCHAR(50),            
    [DataInsercao] NVARCHAR(50)
);
